import sqlite3 as db

conn = db.connect('ksuwallet.db')

conn.execute("""
CREATE TABLE IF NOT EXISTS wallets (
    WALLET_NUMBER TEXT PRIMARY KEY,
    WALLET_TYPE TEXT NOT NULL,    
    BALANCE INTEGER NOT NULL,
    CREATED_AT TEXT NOT NULL
);
""")


conn.execute("""
CREATE TABLE IF NOT EXISTS students (
    STUDENT_ID TEXT PRIMARY KEY,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PHONE TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    WALLET_NUMBER TEXT,
    FOREIGN KEY (WALLET_NUMBER) REFERENCES wallets(WALLET_NUMBER)
);
""")

conn.execute("""
CREATE TABLE IF NOT EXISTS admins (
    ADMIN_ID TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL
);
""")


conn.execute("""
CREATE TABLE IF NOT EXISTS entities (
    ENTITY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT UNIQUE NOT NULL,
    WALLET_NUMBER TEXT,
    FOREIGN KEY (WALLET_NUMBER) REFERENCES wallets(WALLET_NUMBER)
);
""")
conn.execute("""
CREATE TABLE IF NOT EXISTS transactions (
    TRANS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FROM_WALLET TEXT,
    TO_WALLET TEXT,
    AMOUNT INTEGER NOT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (FROM_WALLET) REFERENCES wallets(WALLET_NUMBER),
    FOREIGN KEY (TO_WALLET) REFERENCES wallets(WALLET_NUMBER)
);
""")


